CREATE TABLE "MEMBER" (
	"ID"	varchar2(30)		NOT NULL,
	"name"	varchar2(30)		NULL,
	"ADDRESS"	VARCHAR2(50)		NULL
);

CREATE TABLE "BOARD" (
	"NUM"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(500)		NULL,
	"ID"	varchar2(30)		NOT NULL
);

CREATE TABLE "REPLY_BOARD" (
	"NUM"	NUMBER(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(500)		NULL,
	"ID"	varchar2(30)		NOT NULL,
	"NUM2"	NUMBER(10)		NOT NULL
);

CREATE TABLE "ADMIN" (
	"ID"	varchar2(30)		NOT NULL,
	"REGDATE"	DATE		NULL
);

CREATE TABLE "COURSE" (
	"CNO"	NUMBER(20)		NOT NULL,
	"CTITLE"	VARCHAR2(30)		NULL,
	"CNAME"	VARCHAR2(50)		NULL
);

CREATE TABLE "COURSE_LIST" (
	"ID"	varchar2(30)		NOT NULL,
	"CNO"	NUMBER(20)		NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "REPLY_BOARD" ADD CONSTRAINT "PK_REPLY_BOARD" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COURSE" ADD CONSTRAINT "PK_COURSE" PRIMARY KEY (
	"CNO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_MEMBER_TO_ADMIN_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

